### ISSUE TITLE
Detect when the loader gets finish the required time.

### ISSUE THREAD

**Issue by ambujshukla** [MaheshRS/Download-Indicator#5]
Hi,
I'm using the RMDownloadIndicator and want one solution that how can we detect the loader fills the whole circle means the time when it completed the download bytes.

**Comment by morozkin** [comment]
@ambujshukla, RMDownloadIndicator is a view, so it must not controll progress, it gets progress value and just updates itself. So detection of the ending of your task is a responsibility of an entity which sends progress values to your RMDownloadIndicator instance.

**Comment by ambujshukla** [comment]
Thanks Morozkin:)
